preset: symfony
risky: true
enabled:
  - ordered_imports
  - short_array_syntax
  - concat_with_spaces
  - align_double_arrow
disabled:
  - no_unused_imports
  - concat_without_spaces
  - yoda_style
  - unalign_double_arrow
  - const_separation
finder:
  name: "*.php"
  not-name:
    - "*.blade.php"
    - index.php
    - server.php