preset: symfony
risky: true
enabled:
  - ordered_imports
  - short_array_syntax
  - concat_with_spaces
disabled:
  - unused_use
  - concat_without_spaces
  - yoda_style
finder:
  name: "*.php"
  not-name:
    - "*.blade.php"
    - index.php
    - server.php