preset: laravel
risky: true
enabled:
  - concat_with_spaces
  - align_double_arrow
disabled:
  - no_unused_imports
finder:
  name: "*.php"
  not-name:
    - "*.blade.php"
    - index.php
    - server.php